### ISSUE TITLE
Path must be a string Error in version 2.0.2

### ISSUE THREAD

**Issue by alinex** [juijs/jui-chart#87]
I used the example from https://github.com/juijs/jui-chart to create the chart in nodejs. While using version 1.4.2 it works like it should. But if I use the new version 2.0.2 I get an error:

    TypeError: Path must be a string. Received [ 'dist/ui.min.js', 'dist/ui.min.css', 'dist/ui-jennifer.css' ]
        at assertPath (path.js:7:11)
        at Object.resolve (path.js:1148:7)
        at require (internal/module.js:20:19)

There does this come from?

**Comment by seogi1004** [comment]
Please use the latest version.
https://github.com/juijs/jui-chart/releases/tag/v2.0.4
